# @package _global_
# Dueling Double DQN algorithm configuration

algorithm_name: "dueling_double_dqn"

# Dueling Double DQN specific hyperparameters
dueling_double_dqn:
  # Network parameters
  hidden_size: 512
  learning_rate: 0.0001
  
  # Training parameters
  batch_size: 32
  buffer_size: 100000
  target_update_freq: 1000
  train_freq: 4
  gradient_steps: 1
  
  # Exploration parameters
  exploration_initial_eps: 1.0
  exploration_final_eps: 0.01
  exploration_fraction: 0.1
  
  # Other parameters
  gamma: 0.99
  tau: 1.0  # Hard update
  double_q: true   # Double Q-learning
  dueling: true    # Dueling architecture