# @package _global_
# PPO algorithm configuration

algorithm_name: "ppo"

# PPO specific hyperparameters
ppo:
  # Network parameters
  hidden_size: 64
  learning_rate: 0.00025
  
  # Training parameters
  n_steps: 128
  batch_size: 4
  n_epochs: 4
  gamma: 0.99
  gae_lambda: 0.95
  
  # PPO specific parameters
  clip_range: 0.1
  clip_range_vf: null  # Use same as clip_range if null
  normalize_advantage: true
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5
  
  # Other parameters
  use_sde: false
  sde_sample_freq: -1
  target_kl: null