# @package _global_
# TRPO (Trust Region Policy Optimization) algorithm configuration

algorithm_name: "trpo"

# TRPO specific hyperparameters
trpo:
  # Network parameters
  hidden_size: 64
  learning_rate: 0.001
  
  # Training parameters
  n_steps: 2048
  batch_size: 128
  gamma: 0.99
  gae_lambda: 0.95
  
  # TRPO specific parameters
  max_kl: 0.01
  damping: 0.1
  cg_iters: 10
  backtrack_iters: 10
  backtrack_coeff: 0.8
  
  # Value network parameters
  value_lr: 0.001
  value_train_iters: 80
  
  # Loss coefficients
  entropy_coef: 0.0
  value_loss_coef: 1.0
  
  # Advantage normalization
  normalize_advantage: true
  
  # Line search parameters
  accept_ratio: 0.1